---
name: 'Setup Nim environment'
description: 'Setup a Nim environment and add it to the PATH'
author: 'jiro4989'

inputs:
  nim-version:
    description: >-
      The Nim version to download and use. Example: 2.2.4
    default: '2.2.4'

runs:
  using: 'composite'
  steps:
    - name: Setup nim (Windows)
      if: runner.os == 'Windows'
      shell: bash
      run: |
        echo "install nim ${{ inputs.nim-version }}"
        nim_install_dir="$HOME/.nim_runtime"
        echo "nim install directory: $nim_install_dir"
        mkdir -p "$nim_install_dir"
        cd "$nim_install_dir"
        curl -sSL "https://nim-lang.org/download/nim-${{ inputs.nim-version }}_x64.zip" > nim.zip
        unzip -q nim.zip --strip-components=1
        echo "$nim_install_dir/bin" >> "$GITHUB_PATH"
        echo "$HOME/.nimble/bin" >> "$GITHUB_PATH"

    - name: Setup nim (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        echo "install nim ${{ inputs.nim-version }}"
        nim_install_dir="$HOME/.nim_runtime"
        echo "nim install directory: $nim_install_dir"
        mkdir -p "$nim_install_dir"
        cd "$nim_install_dir"
        curl -sSL "https://nim-lang.org/download/nim-${{ inputs.nim-version }}.tar.xz" > nim.tar.xz
        tar xf nim.tar.xz --strip-components=1
        echo "build nim compiler"
        ./build.sh
        echo "build koch tool"
        ./bin/nim c --noNimblePath --skipUserCfg --skipParentCfg --hints:off koch
        echo "koch boot"
        ./koch boot -d:release --skipUserCfg --skipParentCfg --hints:off
        echo "koch tools"
        ./koch tools --skipUserCfg --skipParentCfg --hints:off
        echo "$nim_install_dir/bin" >> "$GITHUB_PATH"
        echo "$HOME/.nimble/bin" >> "$GITHUB_PATH"

    - name: Setup nim (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        echo "install nim ${{ inputs.nim-version }}"
        nim_install_dir="$HOME/.nim_runtime"
        echo "nim install directory: $nim_install_dir"
        mkdir -p "$nim_install_dir"
        cd "$nim_install_dir"
        curl -sSL "https://nim-lang.org/download/nim-${{ inputs.nim-version }}-linux_x64.tar.xz" > nim.tar.xz
        tar xf nim.tar.xz --strip-components=1
        echo "$nim_install_dir/bin" >> "$GITHUB_PATH"
        echo "$HOME/.nimble/bin" >> "$GITHUB_PATH"

    - name: Print nim directory
      shell: bash
      run: |
        echo "installed nim fullpath: $(which nim)"

    - name: Print nim version
      shell: bash
      run: nim -v

    - name: Print nimble version
      shell: bash
      run: nimble -v
