---
name: 'Setup Nim environment'
description: 'Setup a Nim environment and add it to the PATH'
author: 'treeform'

inputs:
  nim-version:
    description: >-
      The Nim version to download and use. Example: 2.2.6
    default: '2.2.6'

runs:
  using: 'composite'
  steps:
    - name: Setup Nim (Windows)
      if: runner.os == 'Windows'
      shell: bash
      run: |
        set -e
        platform="Windows-X64"
        version="${{ inputs.nim-version }}"
        url="https://github.com/treeform/nimby-nim-builds/releases/download/$version/nim-$version-$platform.zip"
        dest="$HOME/.nimby/nim"
        
        echo "Downloading Nim $version for $platform..."
        curl -sSL "$url" -o nim.zip
        
        echo "Extracting to $dest..."
        rm -rf "$dest"
        mkdir -p "$HOME/.nimby"
        unzip -q nim.zip
        mv "nim-$version-$platform" "$dest"
        
        echo "Adding Nim bin to PATH..."
        echo "$(cygpath -w "$HOME")\.nimby\nim\bin" >> "$GITHUB_PATH"

    - name: Setup Nim (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        set -e
        platform="macOS-ARM64"
        version="${{ inputs.nim-version }}"
        url="https://github.com/treeform/nimby-nim-builds/releases/download/$version/nim-$version-$platform.tar.gz"
        dest="$HOME/.nimby/nim"
        
        echo "Downloading Nim $version for $platform..."
        curl -sSL "$url" -o nim.tar.gz
        
        echo "Extracting to $dest..."
        rm -rf "$dest"
        mkdir -p "$dest"
        tar xf nim.tar.gz --strip-components=1 -C "$dest"
        
        echo "Adding Nim bin to PATH..."
        echo "$dest/bin" >> "$GITHUB_PATH"

    - name: Setup Nim (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        set -e
        arch="$(uname -m)"
        if [ "$arch" = "aarch64" ]; then
          platform="Linux-ARM64"
        else
          platform="Linux-X64"
        fi
        version="${{ inputs.nim-version }}"
        url="https://github.com/treeform/nimby-nim-builds/releases/download/$version/nim-$version-$platform.tar.gz"
        dest="$HOME/.nimby/nim"
        
        echo "Downloading Nim $version for $platform..."
        curl -sSL "$url" -o nim.tar.gz
        
        echo "Extracting to $dest..."
        rm -rf "$dest"
        mkdir -p "$dest"
        tar xf nim.tar.gz --strip-components=1 -C "$dest"
        
        echo "Adding Nim bin to PATH..."
        echo "$dest/bin" >> "$GITHUB_PATH"

    - name: Print nim directory
      shell: bash
      run: |
        echo "installed nim fullpath: $(which nim)"

    - name: Print nim version
      shell: bash
      run: nim -v
