---
name: 'Setup Nim environment'
description: 'Setup a Nim environment and add it to the PATH'
author: 'treeform'

inputs:
  nim-version:
    description: >-
      The Nim version to download and use. Example: 2.2.6
    default: '2.2.6'

runs:
  using: 'composite'
  steps:
    - name: Setup Nim via Nimby (Windows)
      if: runner.os == 'Windows'
      shell: bash
      run: |
        set -e
        echo "Downloading Nimby for Windows..."
        curl -sSL -o nimby.exe "https://github.com/treeform/nimby/releases/download/0.1.13/nimby-Windows-X64.exe"
        chmod +x nimby.exe
        echo "Using Nimby to install Nim ${{ inputs.nim-version }}..."
        ./nimby.exe use "${{ inputs.nim-version }}"
        cp nimby.exe $HOME/.nimby/nim/bin/nimby.exe
        echo "Adding Nim bin to PATH..."
        echo "$(cygpath -w "$HOME")\.nimby\nim\bin" >> "$GITHUB_PATH"

    - name: Setup Nim via Nimby (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        set -e
        arch="$(uname -m)"
        if [ "$arch" = "arm64" ]; then
          NIMBY_URL="https://github.com/treeform/nimby/releases/download/0.1.13/nimby-macOS-ARM64"
        else
          NIMBY_URL="https://github.com/treeform/nimby/releases/download/0.1.13/nimby-macOS-X64"
        fi
        echo "Downloading Nimby for macOS ($arch)..."
        curl -sSL -o nimby "$NIMBY_URL"
        chmod +x nimby
        echo "Using Nimby to install Nim ${{ inputs.nim-version }}..."
        ./nimby use "${{ inputs.nim-version }}"
        cp nimby $HOME/.nimby/nim/bin/nimby
        chmod +x $HOME/.nimby/nim/bin/nimby
        echo "Adding Nim bin to PATH..."
        echo "$HOME/.nimby/nim/bin" >> "$GITHUB_PATH"

    - name: Setup Nim via Nimby (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        set -e
        echo "Downloading Nimby for Linux..."
        curl -sSL -o nimby "https://github.com/treeform/nimby/releases/download/0.1.13/nimby-Linux-X64"
        chmod +x nimby
        echo "Using Nimby to install Nim ${{ inputs.nim-version }}..."
        ./nimby use "${{ inputs.nim-version }}"
        cp nimby $HOME/.nimby/nim/bin/nimby
        chmod +x $HOME/.nimby/nim/bin/nimby
        echo "Adding Nim bin to PATH..."
        echo "$HOME/.nimby/nim/bin" >> "$GITHUB_PATH"

    - name: Print nim directory
      shell: bash
      run: |
        echo "installed nim fullpath: $(which nim)"

    - name: Print nim version
      shell: bash
      run: nim -v

    - name: Print nimby version
      shell: bash
      run: nimby -v
